add : chapter10 doc upload
likelion-ssu/JS-Deep-Dive pull request #10
Opened 2023-01-21 06:06 UTC by Jun99uu

## Summary 🦁
저번 주차에서 제대로 못쓴 것 같아서 이번엔 제대로.. 그리고 쵸콤 일찍(?) 써봤슴다.
**정독 -> 이해 -> 내 말로 치환** 하면서 작성하니 훨씬 이해가 잘되고, 시간도 적게 드는 것 같아요!
여튼 개발할 때(특히 상태관리할 때...) 기초의 기초의 기초가 되는 객체.. 요약 문서 말고 그냥 책으로도 꼭 한 번 읽어보셔유!

## PR Checklist ✏️
- [x] Commit Convention에 맞게 PR Title 작성
- [x] Assignees 확인

2023-01-21 12:22 UTC, da-in requested changes
💩 선생님 [Document Writing Rules](https://github.com/likelion-ssu/JS-Deep-Dive/wiki) 을 반영해야 할 것 같습니다!
내용은 초깔끔해보이는데 10장 공부하고 찬찬히 다시 봐보겠습니다 :)

2023-01-23 12:40 UTC, Jun99uu commented
> 💩 선생님 [Document Writing Rules](https://github.com/likelion-ssu/JS-Deep-Dive/wiki) 을 반영해야 할 것 같습니다! 내용은 초깔끔해보이는데 10장 공부하고 찬찬히 다시 봐보겠습니다 :)

헐 shit.. 당장 고치겠습니다ㅠㅠ 고마워용

2023-01-29 08:58 UTC, yoo-jimin127 approved these changes
🦁 : 자료 정리 너무 깔끔한거 실화냐 ...? 객체 되게 중요한 내용인데 가독성 진짜 좋게 정리 잘 해주신 것 같아요!!
`console.log("ㅎㅇㅋㅋ")` 보고 살짝 킹받았지만 그것이 중규리님의 docs 매력이네요 .. ㄷㄷ

🥕 : 너무 정리 잘 해주셔서 피드백 드릴 사항이 거의 없어요! 자잘한 몇가지 수정 내용 리뷰 남겨두었으니 확인 부탁드림다!
수고하셨어요~~!

2023-01-29 08:58 UTC, yoo-jimin127 commented on JS Deep Dive cheat-sheet/10_객체-리터럴.md
> +  > `일급 객체`란, 다른 객체들에 일반적으로 적용 가능한 연산을 모두 지원하는 객체를 의미함.<br/> > [일급 객체 - 위키피디아](https://ko.wikipedia.org/wiki/%EC%9D%BC%EA%B8%89_%EA%B0%9D%EC%B2%B4)
🥕 : 요기 >이게 하나 더 보여서 제안 드림미다 !!
```suggestion
> `일급 객체`란, 다른 객체들에 일반적으로 적용 가능한 연산을 모두 지원하는 객체를 의미함.   
> [일급 객체 - 위키피디아](https://ko.wikipedia.org/wiki/%EC%9D%BC%EA%B8%89_%EA%B0%9D%EC%B2%B4)
```

2023-01-29 08:58 UTC, yoo-jimin127 commented on JS Deep Dive cheat-sheet/10_객체-리터럴.md
> +## 310.3 프로퍼티
💩 : 잌ㅋㅋㅋㅋㅋㅋ 요기 오타 있는 것 같습니다!!

2023-01-29 08:58 UTC, yoo-jimin127 commented on JS Deep Dive cheat-sheet/10_객체-리터럴.md
> +  > `일급 객체`란, 다른 객체들에 일반적으로 적용 가능한 연산을 모두 지원하는 객체를 의미함.<br/> > [일급 객체 - 위키피디아](https://ko.wikipedia.org/wiki/%EC%9D%BC%EA%B8%89_%EA%B0%9D%EC%B2%B4)
🥕 : 여기 아까랑 같은 부분이라 같이 넣어둘게요!!
```suggestion
> `일급 객체`란, 다른 객체들에 일반적으로 적용 가능한 연산을 모두 지원하는 객체를 의미함.<br/> 
> [일급 객체 - 위키피디아](https://ko.wikipedia.org/wiki/%EC%9D%BC%EA%B8%89_%EA%B0%9D%EC%B2%B4)
```

2023-01-29 10:23 UTC, da-in approved these changes
🦁넘모 깔끔합니다 좋아여

2023-01-29 22:20 UTC, HwangSunBeom approved these changes
ㅋㅋㅋㅋㅋㅋ 예제 코드들이 넘모 귀엽네여어

2023-01-29 23:31 UTC, seocylucky approved these changes
🦁: 깔꼼합니당... 예시가 되게 재밌네여ㅋㅋㅋㅋ 수고하셨어요~~

2023-01-29 23:31 UTC, seocylucky commented on JS Deep Dive cheat-sheet/10_객체-리터럴.md
> +3. 브라우저는 `Nan`, Node.js는 `ReferenceError`인 이유는?
💩: NaN 오타 있숨다!!!

2023-01-29 23:56 UTC, Sang-minKIM reviewed
🦁: 예제도 좀 더 보기 편하게 정리한게 좋아요!

2023-01-29 23:56 UTC, Sang-minKIM commented on JS Deep Dive cheat-sheet/10_객체-리터럴.md
> +  //중괄호 안에0개 이상의 프로퍼티를 정의
💩: "안에 0개" 띄어쓰기 안된 것 같아요!!

2023-01-29 23:56 UTC, Sang-minKIM commented on JS Deep Dive cheat-sheet/10_객체-리터럴.md
> +  //중괄호 안에0개 이상의 프로퍼티를 정의
```suggestion
  //중괄호 안에 0개 이상의 프로퍼티를 정의
```

2023-01-30 09:56 UTC, merged